### ISSUE TITLE
Too slow scripts to add references

### ISSUE THREAD

**Issue by Gupta-Anubhav12** [gita/bhagavad-gita-api#11]
The scripts to add references is very unoptimised and slow because in each iteration it opens a new query for finding the ID of related tuple,
a much faster way is to have a Get All query once and then make a dict out of it and using in memory data to find IDs instead of making new query to server on each pass,

This need to be optimised for future users and contributors
Thanks
Hare Krishna

**Comment by aahnik** [comment]
> a much faster way is to have a Get All query once and then make a dict out of it and using in-memory data to find IDs instead of making a new query to the server on each pass,

yup! i was worried about the speed. this is a great solution. what if we save the data in json in that format ? I mean the json files would contain the ids. 

1. we may write script to take the old json and convert to the new format. so that, the referencing scripts are not needed anymore
2. we reference everytime using the smarter way @Gupta-Anubhav12 suggested.

1 or 2 ? which one should we do ?

**Comment by Gupta-Anubhav12** [comment]
as planned in meeting today we can have choice 1 as so let's close this issue and merge the PR
